name: ceal_chronicler_f
description: A Flutter Project for a Windows/Android app for keeping track of characters, locations and events in a book or role playing game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  get_it: ^7.2.0
  event_bus: ^2.0.0
  uuid: ^3.0.7
  optional: ^6.1.0
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  image_path: "assets/images/CealChroniclerIcon.png"
  adaptive_icon_background: "assets/images/CealChroniclerAppIconBackground.png"
  adaptive_icon_foreground: "assets/images/CealChroniclerAppIconForeground.png"
  windows:
    generate: true
    image_path: "assets/images/CealChroniclerIcon.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/images/CealChroniclerIcon.png"
    background_color: "#007fff"
    theme_color: "#007fff"
