name: ceal_chronicler_f
description: A Flutter Project for a Windows/Android app for keeping track of characters, locations and events in a book or role playing game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  get_it: ^8.0.3
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.2
  path_provider: ^2.1.5 #saving on mobile
  file_picker: ^8.1.7 #saving for windows and loading for all

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/CealChroniclerLogo.png"
  adaptive_icon_foreground: "assets/images/CealChroniclerLogoFG.png"
  adaptive_icon_background: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/CealChroniclerLogo.png"
    icon_size: 256